### PR TITLE
[Engineering] Management: how to run the Backlog Grooming effectively

### PR DESCRIPTION
**Pull request by nhuthm**
- Sharing the way that the Setel team is running with the Backlog Grooming

### CODE REVIEW

**Review by monotykamary — CHANGES_REQUESTED** [review]
The note mentions the company Setel. Have we asked permission to use their company brand in the note?

**Comment by nhuthm** [comment]
It is actually from our side advice as well @monotykamary , I think I will use another image for this one 🤔 what do you think about it

**Comment by monotykamary** [comment]
If there isn't a reason or we don't have permission to use their brand, we should just omit it from the note.

**Comment by nhuthm** [comment]
Alright, let me update this one mate, thanks @monotykamary 🙏

**Comment by nhuthm** [comment]
@monotykamary please help me to take another review, just updated 🙏

**Review by monotykamary — APPROVED** [review]
LGTM

**Pull request merged**
